In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
## data
myfile = requests.get('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv')
open('data', 'wb').write(myfile.content)
confirmed_global_df = pd.read_csv('data')
country = 'India'

## pre-processing
confirmed_country = confirmed_global_df[confirmed_global_df['Country/Region'] == country].reset_index(drop=True)
df = confirmed_country.melt(id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], 
                            value_vars=confirmed_global_df.columns[4:], var_name='Date', value_name='RecoveredCases')
df2 = df.groupby(["Date", "Country/Region"])[['Date', 'Country/Region', 'RecoveredCases']].sum().reset_index()
df2.columns = ['Date', 'Country', 'Recovered']
df2['Date'] = pd.to_datetime(df2['Date'])

#sorting data
df2.sort_values(by=['Date'], inplace=True)

# reseting index
df2.reset_index(drop=True, inplace=True)

# setting up data
recovered = []
recovered.append(df2['Recovered'][0])
for i in range(1, len(df2)):
    recovered.append(abs(df2['Recovered'][i] - df2['Recovered'][i-1]))
df2['recovered'] = recovered

In [3]:
df2

          Date Country  Recovered  recovered
0   2020-01-22   India          0          0
1   2020-01-23   India          0          0
2   2020-01-24   India          0          0
3   2020-01-25   India          0          0
4   2020-01-26   India          0          0
..         ...     ...        ...        ...
823 2022-04-24   India          0          0
824 2022-04-25   India          0          0
825 2022-04-26   India          0          0
826 2022-04-27   India          0          0
827 2022-04-28   India          0          0

[828 rows x 4 columns]